# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-06 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbodegas', '0002_auto_20190705_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='serie',
            field=models.CharField(max_length=30),
        ),
    ]
